'use client';
import { useState } from "react";
import Head from 'next/head'
import emailjs from '@emailjs/browser';
import { BsFillMoonStarsFill, BsGithub } from 'react-icons/bs';
import { AiFillLinkedin } from 'react-icons/ai';
import Image from "next/image";
import mypic from '../public/mypic.png'
import html from '../public/html.png'
import boot from '../public/bootstrap.png'
import css from '../public/css.png'
import java from '../public/java.png'
import js from '../public/js.png'
import mern from '../public/mern.png'
import python from '../public/python.png'
import tailwind from '../public/tailwind.png'
import nba from '../public/nba.png'
import ai from '../public/ai.png'
import pirate from '../public/pirate.png'
import thread from '../public/thread.png'


export default function Home() {

  const [darkMode, setDarkMode] = useState(false);

  const [flash, setFlash] = useState(false);


  const sendEmail = (e) => {
    e.preventDefault();

    emailjs.sendForm('service_knqyd4d', 'template_2a893ik', e.target, 'WD80t--JdSu_jSQEZ')
      .then((result) => {
        console.log(result.text);
        console.log("message sent")
        setFlash(true)
      }, (error) => {
        console.log(error.text);
      });
    e.target.reset()
  };


  return (

    <div className={darkMode ? "dark" : ""}>

      <Head>
        <title>Jason Schneck Portfolio</title>
        <meta name="description" content="Generated by me"></meta>
        <link rel="icon" href="/favicon.ico"></link>
      </Head>

      {/* Nav Bar -  */}
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>

        <section className="min-h-screen">

          <nav className='py-10 mb-6 flex justify-end'>


            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl dark:text-white" />
              </li>

              <li>
                <button className='bg-gradient-to-r from-red-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'
                  onClick={() => window.open("https://app.diplomasafe.com/en-US/diploma/d84ace316839926d3384674848aae14c30eadc5f1")}>
                  Diploma
                </button>
              </li>

              <li>
                <button className='bg-gradient-to-r from-purple-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' 
                onClick={() => window.open("https://docs.google.com/document/d/1aJLdWWLDxKT2-7f_ckQv-H1fTfmqkpLj/edit")}>
                  Resume
                </button>
              </li>

            </ul>

          </nav>

          {/* Info Display -  */}

          <div className='text-center p-10'>

            <h2 className='text-4xl py-2 text-teal-600 font-medium md:text-6xl'>Jason Schneck</h2>
            <h3 className='text-2xl py-2 md:text-3xl text-teal-600'>Full Stack Developer</h3>
            <p className='text-md leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white'>
              As a seasoned full-stack developer, I proudly hold a prestigious degree from <span className="text-teal-600">Coding Dojo</span>,
              a testament to my exceptional skills and <span className="text-teal-600">commitment</span> to the field. My expertise extends to
              offering comprehensive full-stack services, delivering <span className="text-teal-600">innovative</span> and reliable solutions to
              clients. Beyond my professional pursuits, I am an individual with diverse interests that
              enrich my life. A <span className="text-teal-600">passionate</span> enthusiast of both watching and actively participating in sports,
              I find inspiration in the spirit of <span className="text-teal-600">competition</span> and <span className="text-teal-600">teamwork</span>. My love for music serves as a
              creative outlet, filling my leisure time with delightful melodies. Click the <span className="text-teal-600">LinkedIn</span> picture to be redirected
              to my page and look around! Click the <span className="text-teal-600">GitHub</span> picture to find more code/projects I have done!
            </p>

          </div>

          <div className='text-5xl flex space-x-6 justify-center pb-5 text-gray-600 dark:text-white'>
            <button onClick={() => window.open("https://www.linkedin.com/in/jason-schneck-0b7722263/")}><AiFillLinkedin /></button>
            <button onClick={() => window.open("https://github.com/Jason-Schneck?tab=repositories")}><BsGithub /></button>
          </div>

          <div className='relative mx-auto h-60 w-60 rounded-full px-8'>
            <Image src={mypic} alt="" />
          </div>

        </section>

        {/* Services I Offer Section -  */}

        <section>

          <div>

            <h3 className='text-3xl pt-20  dark:text-white'>Services I offer:</h3>

            <div className='flex justify-between py-10'>
              <Image src={html} className='h-20 w-20' alt="" />
              <Image src={boot} className='h-20 w-20 rounded-md' alt="" />
              <Image src={css} className='h-20 w-20 rounded-md' alt="" />
              <Image src={java} className='h-20 w-20' alt="" />
            </div>

            <div className='flex justify-between py-10'>
              <Image src={mern} className='h-20 w-20' alt="" />
              <Image src={python} className='h-20 w-20' alt="" />
              <Image src={js} className='h-20 w-20 rounded-md' alt="" />
              <Image src={tailwind} className='h-20 w-20 rounded-md' alt="" />
            </div>


          </div>

          {/* Card 1 -  */}

          <h3 className='text-3xl py-1 pt-10 dark:text-white'>Projects:</h3>
          <div className="lg:flex gap-10">

            <div className='text-center shadow-lg shadow-teal-300 p-10 rounded-xl my-10'>
              <Image className='mx-auto w-40 h-40 pl-10' src={nba} alt="" />
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white'>NBA Metaverse</h3>

              <p className='text-sm  dark:text-white' >
                Experience a beautiful NBA Metaverse
                using <span className="text-teal-600">animations</span> .
                Delve into NBA worlds and explore their era. 
                Discover fascinating members of the metaverse with the tracking map. Keep 
                up to date <span className="text-teal-600">conveniently</span> with 
                a news layout, and even see the winner of the 
                <span className="text-teal-600"> 2023 Finals!</span>
              </p>

              <h4 className="py-4 text-teal-600">Tools Used:</h4>
              <p className="text-gray-800 dark:text-white" >React</p>
              <p className="text-gray-800 dark:text-white" >Next.Js</p>
              <p className="text-gray-800 dark:text-white" >Tailwind CSS</p>

              <button className='bg-gradient-to-r from-blue-500 to-red-500 text-white rounded-md mt-5 p-1' 
                onClick={() => window.open("https://nbametaverse.netlify.app/")}
              >
               Visit Website
              </button>

            </div>

            {/* Card 2 -  */}

            <div className='text-center shadow-lg shadow-teal-300 p-10 rounded-xl my-10'>

              <Image className="mx-auto w-40 h-40 rounded-lg" src={ai} alt="" />
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white'>AI Summarizer</h3>

              <p className='text-sm dark:text-white'>
              In today's fast-paced world, the ability to quickly extract <span className='text-teal-600'> key insights </span>
              from extensive articles is invaluable. Our cutting-edge <span className='text-teal-600'> AI technology </span>  
              employs advanced natural language processing algorithms to meticulously
              analyze and distill lengthy articles into <span className='text-teal-600'> concise, coherent summaries, </span>  
              while preserving the essential meaning and context.
              </p>

              <h4 className="py-4 text-teal-600">Tools Used:</h4>
              <p className="text-gray-800 dark:text-white" >React</p>
              <p className="text-gray-800 dark:text-white" >Next.js</p>
              <p className="text-gray-800 dark:text-white" >Tailwind CSS</p>
              <p className="text-gray-800 dark:text-white" >API</p>

              <button className='bg-gradient-to-r from-amber-800 to-orange-500 text-white rounded-md mt-5 p-1' 
                onClick={() => window.open("https://gpt-summary.netlify.app/")}
              >
               Visit Website
              </button>

            </div>

            {/* Card 3 -  */}

            <div className='text-center shadow-lg shadow-teal-300 p-10 rounded-xl my-10'>
              <Image className="mx-auto w-40 h-40 rounded-lg" src={thread} alt="" />
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white'>Threads</h3>
              <p className='text-sm dark:text-white'>
                Welcome to my <span className='text-teal-600'> full stack application </span> , called Threads. 
                It is my great effort to recreate this new application that blew up over night. 
                This social media app allows users to sign
                in using <span className='text-teal-600'> clerk </span>, then setting up their account.
                 After this, you can view other's posts, 
                 <span className='text-teal-600'> comment </span> on them, or even join a 
                 <span className='text-teal-600'> community </span>. This innovative social media app
                changes how people connect!
              </p>
              <h4 className="py-4 text-teal-600">Tools Used:</h4>
              <p className="text-gray-800 dark:text-white" >Next.Js</p>
              <p className="text-gray-800 dark:text-white" >Tailwind CSS</p>
              <p className="text-gray-800 dark:text-white" >MERN</p>
              <p className="text-gray-800 dark:text-white" >Clerk</p>
              <p className="text-gray-800 dark:text-white mt-2" >*Still in Production*</p>

              <button className='bg-gradient-to-r from-purple-600 to-blue-400 text-white rounded-md mt-5 p-1' 
                onClick={() => window.open("https://js-threads-app.vercel.app/")}
              >
               Visit Website
              </button>
            </div>

          </div>

          {/* Contact Me -  */}

          <section>

            <h2 className="text-3xl py-1 mt-20 mb-7 dark:text-white">Contact Me</h2>

            <div className='text-center shadow-xl shadow-teal-300 p-10 rounded-xl'>

              <form onSubmit={sendEmail}>

                <p className='text-lg dark:text-white mb-5'>Full Name:</p>
                <input className='text-white rounded-md mb-5 p-2 bg-gray-700 dark:text-white' type="text" placeholder='Full Name' name='user_name' required />

                <p className='text-lg dark:text-white mb-5'>Email:</p>
                <input className='text-white rounded-md mb-5 p-2 bg-gray-700 dark:text-white' type="email" placeholder='Email' name='user_email' required />

                <p className='text-lg dark:text-white mb-5'>Subject:</p>
                <textarea className='text-white rounded-md mb-5 p-5 w-60 h-60 bg-gray-700 dark:text-white' placeholder='Subject' name='subject' required />

                <div>
                  <button className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md'>Send Message</button>
                  <h3 className="dark:text-white pt-5">{flash ? "Message Sent ✅" : ""}</h3>
                </div>

              </form>

            </div>

          </section>


        </section>


      </main>


    </div>
  )
}
